steps:
  # Build the Docker image with --no-cache
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '-f'
      - 'Dockerfile'
      - '-t'
      - 'us-central1-docker.pkg.dev/gcp-sandbox-field-eng/iris-artifacts/iris-uc-server:latest'
      - '.'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/gcp-sandbox-field-eng/iris-artifacts/iris-uc-server:latest'

images:
  - 'us-central1-docker.pkg.dev/gcp-sandbox-field-eng/iris-artifacts/iris-uc-server:latest'

timeout: 1200s
